name: Generate Javadoc

on: workflow_dispatch

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app  # appディレクトリでコマンド実行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ../gradlew

      - name: Generate Javadoc
        run: ../gradlew javadoc

      - name: Upload Javadoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: app/build/docs/javadoc
